AMAZON_S3_ACCESS_KEY: '{{ localsettings_private.AMAZON_S3_ACCESS_KEY | default(None)
  }}'
AMAZON_S3_SECRET_KEY: '{{ localsettings_private.AMAZON_S3_SECRET_KEY | default(None)
  }}'
AMQP_PASSWORD: '{{ secrets.AMQP_PASSWORD | default(None) }}'
AMQP_USER: '{{ secrets.AMQP_USER | default(None) }}'
APPCUES_ID: '{{ localsettings_private.APPCUES_ID | default('''', true) }}'
APPCUES_KEY: '{{ localsettings_private.APPCUES_KEY | default('''', true) }}'
BANK_ACCOUNT_NUMBER: '{{ localsettings_private.BANK_ACCOUNT_NUMBER | default(None)
  }}'
BANK_ROUTING_NUMBER_ACH: '{{ localsettings_private.BANK_ROUTING_NUMBER_ACH | default('''')
  }}'
BANK_ROUTING_NUMBER_WIRE: '{{ localsettings_private.BANK_ROUTING_NUMBER_WIRE | default('''')
  }}'
BITLY_APIKEY: '{{ localsettings_private.BITLY_APIKEY | default('''') }}'
BITLY_LOGIN: '{{ localsettings_private.BITLY_LOGIN | default('''') }}'
BITLY_OAUTH_TOKEN: '{{ localsettings_private.BITLY_OAUTH_TOKEN | default('''') }}'
BOOKKEEPER_CONTACT_EMAILS: '{{ localsettings_private.BOOKKEEPER_CONTACT_EMAILS | default(None)
  }}'
CELERY_FLOWER_URL: http://192.168.122.3:5555
CELERY_HEARTBEAT_THRESHOLDS:
  analytics_queue: 1800
  async_restore_queue: 60
  background_queue: 600
  case_import_queue: 60
  case_rule_queue: 3600
  celery: 60
  celery_periodic: 600
  email_queue: 30
  export_download_queue: 30
  repeat_record_queue: 3600
  saved_exports_queue: 21600
  ucr_queue: 3600
COUCH_PASSWORD: '{{ localsettings_private.COUCH_PASSWORD | default(None) }}'
COUCH_USERNAME: '{{ localsettings_private.COUCH_USERNAME | default(None) }}'
DATADOG_API_KEY: '{{ secrets.DATADOG_API_KEY | default(None) }}'
DATADOG_APP_KEY: '{{ secrets.DATADOG_APP_KEY | default(None) }}'
DEFAULT_POSTGRESQL_HOST: 192.168.122.4
DRIFT_ID: '{{ localsettings_private.DRIFT_ID | default('''', true) }}'
DROPBOX_KEY: '{{ localsettings_private.DROPBOX_KEY | default(None) }}'
DROPBOX_SECRET: '{{ localsettings_private.DROPBOX_SECRET | default(None) }}'
ECRYPTFS_PASSWORD: '{{ secrets.ECRYPTFS_PASSWORD | default(None) }}'
EMAIL_LOGIN: '{{ localsettings_private.EMAIL_LOGIN | default(None) }}'
EMAIL_PASSWORD: '{{ localsettings_private.EMAIL_PASSWORD | default(None) }}'
ES_SETTINGS:
  case_search: {}
  default:
    number_of_replicas: 0
  hqapps: {}
  hqcases: {}
  hqdomains: {}
  hqgroups: {}
  hqusers: {}
  ledgers: {}
  report_cases: {}
  report_xforms: {}
  smslogs: {}
  xforms: {}
FORMPLAYER_INTERNAL_AUTH_KEY: '{{ localsettings_private.FORMPLAYER_INTERNAL_AUTH_KEY
  | default(None) }}'
FULLSTORY_ID: '{{ localsettings_private.FULLSTORY_ID | default('''', true) }}'
GMAPS_API_KEY: '{{ localsettings_private.GMAPS_API_KEY | default('''') }}'
GOOGLE_ANALYTICS_API_ID: '{{ localsettings_private.GOOGLE_ANALYTICS_API_ID | default('''',
  true) }}'
GREENHOUSE_API_KEY: '{{ localsettings_private.GREENHOUSE_API_KEY | default(None) }}'
HQ_PRIVATE_KEY: '{{ localsettings_private.HQ_PRIVATE_KEY | default(None) }}'
HUBSPOT_API_ID: '{{ localsettings_private.HUBSPOT_API_ID | default('''', true) }}'
HUBSPOT_API_KEY: '{{ localsettings_private.HUBSPOT_API_KEY | default('''', true) }}'
J2ME_SITE_HOST: null
JAR_KEY_PASS: '{{ localsettings_private.JAR_KEY_PASS | default('''') }}'
JAR_STORE_PASS: '{{ localsettings_private.JAR_STORE_PASS | default('''') }}'
KISSMETRICS_KEY: '{{ localsettings_private.KISSMETRICS_KEY | default('''', true) }}'
KSPLICE_ACTIVATION_KEY: '{{ secrets.KSPLICE_ACTIVATION_KEY | default(None) }}'
LOAD_BALANCED_APPS: {}
MAPBOX_ACCESS_TOKEN: '{{ localsettings_private.MAPBOX_ACCESS_TOKEN | default('''')
  }}'
MAPS_LAYERS: '{{ localsettings_private.MAPS_LAYERS | default(None) }}'
MOBILE_INTEGRATION_TEST_TOKEN: '{{ localsettings_private.MOBILE_INTEGRATION_TEST_TOKEN
  | default(None) }}'
NO_WWW_SITE_HOST: null
OLD_AMQP_PASSWORD: '{{ secrets.OLD_AMQP_PASSWORD | default(AMQP_PASSWORD) | default(None)
  }}'
OLD_AMQP_USER: '{{ secrets.OLD_AMQP_USER | default(AMQP_USER) | default(None) }}'
OPEN_EXCHANGE_RATES_API_ID: '{{ localsettings_private.OPEN_EXCHANGE_RATES_API_ID |
  default(None) }}'
REDIS_PASSWORD: '{{ localsettings_private.REDIS_PASSWORD | default(None) }}'
REPORTING_DATABASES:
  ucr: ucr
RETURN_PATH_EMAIL_PASSWORD: '{{ localsettings_private.RETURN_PATH_EMAIL_PASSWORD |
  default(None) }}'
SECRET_KEY: '{{ localsettings_private.SECRET_KEY }}'
SENTRY_API_KEY: '{{ localsettings_private.SENTRY_API_KEY | default(None) }}'
SENTRY_DSN: '{{ localsettings_private.SENTRY_DSN | default(None) }}'
SENTRY_PRIVATE_KEY: '{{ localsettings_private.SENTRY_PRIVATE_KEY | default(None) }}'
SENTRY_PROJECT_ID: '{{ localsettings_private.SENTRY_PROJECT_ID | default(None) }}'
SENTRY_PUBLIC_KEY: '{{ localsettings_private.SENTRY_PUBLIC_KEY | default(None) }}'
SENTRY_QUERY_URL: '{{ localsettings_private.SENTRY_QUERY_URL | default(None) }}'
SEPARATE_FORM_PROCESSING_DBS: true
SEPARATE_SYNCLOGS_DB: true
SIMPLE_API_KEYS: '{{ localsettings_private.SIMPLE_API_KEYS | default(None) }}'
SITE_HOST: cluster.commcarehq.test
SNS_EMAIL_EVENT_SECRET: '{{ localsettings_private.SNS_EMAIL_EVENT_SECRET | default(None)
  }}'
STRIPE_PRIVATE_KEY: '{{ localsettings_private.STRIPE_PRIVATE_KEY | default(None) }}'
STRIPE_PUBLIC_KEY: '{{ localsettings_private.STRIPE_PUBLIC_KEY | default(None) }}'
SUMOLOGIC_URL: '{{ localsettings_private.SUMOLOGIC_URL | default(None) }}'
TRANSIFEX_API_TOKEN: '{{ localsettings_private.TRANSIFEX_API_TOKEN | default(None)
  }}'
airflow_flask_key: '{{ secrets.AIRFLOW_FLASK_KEY | default(None) }}'
airflow_secret_key: '{{ secrets.AIRFLOW_SECRET_KEY | default(None) }}'
app_processes_config:
  additional_no_proxy_hosts: null
  celery_command_prefix: ''
  celery_heartbeat_thresholds: {}
  celery_processes:
    192.168.122.3:
      beat:
        concurrency: 1
        max_tasks_per_child: null
        num_workers: 1
        optimize: false
        pooling: prefork
        prefetch_multiplier: 4
      flower:
        concurrency: 1
        max_tasks_per_child: null
        num_workers: 1
        optimize: false
        pooling: prefork
        prefetch_multiplier: 4
      ? repeat_record_queue,celery,case_import_queue,background_queue,export_download_queue,saved_exports_queue,analytics_queue,ucr_queue,async_restore_queue,email_queue,case_rule_queue,celery_periodic
      : concurrency: 1
        max_tasks_per_child: null
        num_workers: 1
        optimize: false
        pooling: prefork
        prefetch_multiplier: 4
    None:
      reminder_case_update_queue:
        concurrency: 1
        max_tasks_per_child: null
        num_workers: 1
        optimize: false
        pooling: prefork
        prefetch_multiplier: 4
      reminder_rule_queue:
        concurrency: 1
        max_tasks_per_child: null
        num_workers: 1
        optimize: false
        pooling: prefork
        prefetch_multiplier: 4
      sms_queue:
        concurrency: 1
        max_tasks_per_child: null
        num_workers: 1
        optimize: false
        pooling: prefork
        prefetch_multiplier: 4
  datadog_pythonagent: null
  django_bind: 0.0.0.0
  django_command_prefix: ''
  django_port: 9010
  flower_port: 5555
  formplayer_command_args: ''
  formplayer_g1heapregionsize: 2m
  formplayer_maxmetaspacesize: 512m
  formplayer_memory: 1024m
  gunicorn_workers_factor: 1
  gunicorn_workers_static_factor: 0
  http_proxy: null
  management_commands:
    192.168.122.3: {}
  pillows:
    192.168.122.3:
      AppDbChangeFeedPillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
      ApplicationToElasticsearchPillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
      CacheInvalidatePillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
      DefaultChangeFeedPillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
      DomainDbKafkaPillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
      KafkaDomainPillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
      LedgerToElasticsearchPillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
      SqlSMSPillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
      UpdateUserSyncHistoryPillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
      UserCacheInvalidatePillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
      UserGroupsDbKafkaPillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
      case-pillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
      group-pillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
      user-pillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
      xform-pillow:
        dedicated_migration_process: false
        num_processes: 1
        start_process: 0
  service_blacklist: []
auditcare_db_name: commcarehq_auditcare
authorized_keys_dir: /home/nhooper/environments/_authorized_keys/
celery_queues:
- analytics_queue
- async_restore_queue
- background_queue
- beat
- case_rule_queue
- case_import_queue
- celery
- celery_periodic
- dashboard_comparison_queue
- email_queue
- export_download_queue
- flower
- icds_aggregation_queue
- icds_dashboard_reports_queue
- linked_domain_queue
- logistics_background_queue
- logistics_reminder_queue
- reminder_case_update_queue
- reminder_case_update_bulk_queue
- reminder_queue
- reminder_rule_queue
- repeat_record_queue
- saved_exports_queue
- sumologic_logs_queue
- send_report_throttled
- sms_queue
- submission_reprocessing_queue
- ucr_indicator_queue
- ucr_queue
- user_import_queue
- ush_background_tasks
commcarehq_main_db_name: commcarehq
commcarehq_repository: https://github.com/dimagi/commcare-hq.git
deploy_env: cluster
deploy_event_token: '{{ deploy_event_token | default(None) }}'
deploy_keys: {}
dev_users:
  absent: []
  present:
  - nhooper
env_files_dir: /home/nhooper/environments/cluster/files
env_monitoring_id: cluster
extra_sites: []
fake_ssl_cert: true
form_processing_proxy_db_name: commcarehq_proxy
form_processing_proxy_standby_db_name: commcarehq_proxy_standby
formplayer_db_name: formplayer
formplayer_sentry_dsn: '{{ secrets.FORMPLAYER_SENTRY_DSN | default(None) }}'
git_repositories: []
host_settings: {}
known_hosts_file: /home/nhooper/environments/cluster/known_hosts
letsencrypt_cas_ssl: false
letsencrypt_cchq_ssl: true
new_release_name: 2021-12-07_17.28
nginx_block_ips: []
nginx_combined_cert_value: null
nginx_hsts_max_age: null
nginx_key_value: null
nginx_max_worker_connection: 512
nginx_worker_rlimit_nofile: '{{ nofile_limit }}'
old_s3_blob_db_access_key: '{{ secrets.OLD_S3_BLOB_DB_ACCESS_KEY | default(None) }}'
old_s3_blob_db_secret_key: '{{ secrets.OLD_S3_BLOB_DB_SECRET_KEY | default(None) }}'
pg_repack: {}
pgbouncer_default_pool: 90
pgbouncer_max_connections: 200
pgbouncer_pool_mode: transaction
pgbouncer_pool_timeout: 1
pgbouncer_reserve_pool: 5
postgres_users: '{{ secrets.POSTGRES_USERS | default(None) }}'
postgresql_dbs:
  all:
  - &id001
    create: true
    django_alias: default
    django_migrate: true
    host: 192.168.122.4
    name: commcarehq
    options: {}
    password: '{{ postgres_users.commcare.password }}'
    pg_config: []
    pgbouncer_endpoint: 192.168.122.4
    pgbouncer_hosts:
    - 192.168.122.4
    port: 6432
    query_stats: false
    user: '{{ postgres_users.commcare.username }}'
  - &id002
    create: true
    django_alias: p1
    django_migrate: true
    host: 192.168.122.4
    name: commcarehq_p1
    options: {}
    password: '{{ postgres_users.commcare.password }}'
    pg_config: []
    pgbouncer_endpoint: 192.168.122.4
    pgbouncer_hosts:
    - 192.168.122.4
    port: 6432
    query_stats: false
    shards:
    - 0
    - 511
    user: '{{ postgres_users.commcare.username }}'
  - &id003
    create: true
    django_alias: p2
    django_migrate: true
    host: 192.168.122.4
    name: commcarehq_p2
    options: {}
    password: '{{ postgres_users.commcare.password }}'
    pg_config: []
    pgbouncer_endpoint: 192.168.122.4
    pgbouncer_hosts:
    - 192.168.122.4
    port: 6432
    query_stats: false
    shards:
    - 512
    - 1023
    user: '{{ postgres_users.commcare.username }}'
  - &id004
    create: true
    django_alias: proxy
    django_migrate: true
    host: 192.168.122.4
    name: commcarehq_proxy
    options: {}
    password: '{{ postgres_users.commcare.password }}'
    pg_config: []
    pgbouncer_endpoint: 192.168.122.4
    pgbouncer_hosts:
    - 192.168.122.4
    port: 6432
    query_stats: false
    user: '{{ postgres_users.commcare.username }}'
  - &id005
    create: true
    django_alias: synclogs
    django_migrate: true
    host: 192.168.122.4
    name: commcarehq_synclogs
    options: {}
    password: '{{ postgres_users.commcare.password }}'
    pg_config: []
    pgbouncer_endpoint: 192.168.122.4
    pgbouncer_hosts:
    - 192.168.122.4
    port: 6432
    query_stats: false
    user: '{{ postgres_users.commcare.username }}'
  - &id006
    create: true
    django_alias: ucr
    django_migrate: false
    host: 192.168.122.4
    name: commcarehq_ucr
    options: {}
    password: '{{ postgres_users.commcare.password }}'
    pg_config: []
    pgbouncer_endpoint: 192.168.122.4
    pgbouncer_hosts:
    - 192.168.122.4
    port: 6432
    query_stats: false
    user: '{{ postgres_users.commcare.username }}'
  - &id007
    create: true
    django_alias: null
    django_migrate: true
    host: 192.168.122.4
    name: formplayer
    options: {}
    password: '{{ postgres_users.commcare.password }}'
    pg_config: []
    pgbouncer_endpoint: 192.168.122.4
    pgbouncer_hosts:
    - 192.168.122.4
    port: 6432
    query_stats: false
    user: '{{ postgres_users.commcare.username }}'
  auditcare: null
  by_pgbouncer_host:
    192.168.122.4:
    - *id001
    - *id002
    - *id003
    - *id004
    - *id005
    - *id006
    - *id007
  custom: []
  form_processing:
    partitions:
      p1:
        create: true
        django_alias: p1
        django_migrate: true
        host: 192.168.122.4
        name: commcarehq_p1
        options: {}
        password: '{{ postgres_users.commcare.password }}'
        pg_config: []
        pgbouncer_endpoint: 192.168.122.4
        pgbouncer_hosts:
        - 192.168.122.4
        port: 6432
        query_stats: false
        shards:
        - 0
        - 511
        user: '{{ postgres_users.commcare.username }}'
      p2:
        create: true
        django_alias: p2
        django_migrate: true
        host: 192.168.122.4
        name: commcarehq_p2
        options: {}
        password: '{{ postgres_users.commcare.password }}'
        pg_config: []
        pgbouncer_endpoint: 192.168.122.4
        pgbouncer_hosts:
        - 192.168.122.4
        port: 6432
        query_stats: false
        shards:
        - 512
        - 1023
        user: '{{ postgres_users.commcare.username }}'
    proxy:
      create: true
      django_alias: proxy
      django_migrate: true
      host: 192.168.122.4
      name: commcarehq_proxy
      options: {}
      password: '{{ postgres_users.commcare.password }}'
      pg_config: []
      pgbouncer_endpoint: 192.168.122.4
      pgbouncer_hosts:
      - 192.168.122.4
      port: 6432
      query_stats: false
      user: '{{ postgres_users.commcare.username }}'
    proxy_standby:
      create: true
      django_alias: proxy_standby
      django_migrate: true
      host: null
      name: commcarehq_proxy_standby
      options: {}
      password: null
      pg_config: []
      pgbouncer_endpoint: null
      pgbouncer_hosts: []
      port: null
      query_stats: false
      user: null
  formplayer:
    create: true
    django_alias: null
    django_migrate: true
    host: 192.168.122.4
    name: formplayer
    options: {}
    password: '{{ postgres_users.commcare.password }}'
    pg_config: []
    pgbouncer_endpoint: 192.168.122.4
    pgbouncer_hosts:
    - 192.168.122.4
    port: 6432
    query_stats: false
    user: '{{ postgres_users.commcare.username }}'
  main:
    create: true
    django_alias: default
    django_migrate: true
    host: 192.168.122.4
    name: commcarehq
    options: {}
    password: '{{ postgres_users.commcare.password }}'
    pg_config: []
    pgbouncer_endpoint: 192.168.122.4
    pgbouncer_hosts:
    - 192.168.122.4
    port: 6432
    query_stats: false
    user: '{{ postgres_users.commcare.username }}'
  standby: []
  synclogs:
    create: true
    django_alias: synclogs
    django_migrate: true
    host: 192.168.122.4
    name: commcarehq_synclogs
    options: {}
    password: '{{ postgres_users.commcare.password }}'
    pg_config: []
    pgbouncer_endpoint: 192.168.122.4
    pgbouncer_hosts:
    - 192.168.122.4
    port: 6432
    query_stats: false
    user: '{{ postgres_users.commcare.username }}'
  ucr:
    create: true
    django_alias: ucr
    django_migrate: false
    host: 192.168.122.4
    name: commcarehq_ucr
    options: {}
    password: '{{ postgres_users.commcare.password }}'
    pg_config: []
    pgbouncer_endpoint: 192.168.122.4
    pgbouncer_hosts:
    - 192.168.122.4
    port: 6432
    query_stats: false
    user: '{{ postgres_users.commcare.username }}'
postgresql_effective_cache_size: 3GB
postgresql_max_connections: 100
postgresql_max_stack_depth: 4MB
postgresql_shared_buffers: 1GB
primary_ssl_env: null
replications: []
s3_access_key: '{{ secrets.S3_ACCESS_KEY | default(None) }}'
s3_secret_key: '{{ secrets.S3_SECRET_KEY | default(None) }}'
slack_token: '{{ slack_token | default(None) }}'
special_sites: []
synclogs_db_name: commcarehq_synclogs
trusted_proxies: []
ucr_db_name: commcarehq_ucr
